### ISSUE TITLE
Do not abort if ~/.aws/credentials are not present

### ISSUE THREAD

**Issue by mwpolcik** [Appliscale/perun#158]
If `~/aws.credentials` are not present you can't validate your template. This is not a good approach, because:
1. You might want to run perun on ec2 with instance profile when credentials are passed in a different way. Maybe perun should behave like aws-cli and look for credentials in many locations e.g. from environment variables etc.

2. You may want to just check if template is valid using offline validation, in that case just perform offline validation and inform user that perun was not able to find credentials to make call to aws for 
online validation.

**Comment by maxiwoj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Perform validation even when .aws/credentials are not present](https://trello.com/c/eN4pM5VQ/60-perform-validation-even-when-aws-credentials-are-not-present)

**Comment by maxiwoj** [comment]
closed by https://github.com/Appliscale/perun/pull/172
