### ISSUE TITLE
Generate parameters file based on Parameters section inside the Template 

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#16]
In order to use `aws-cli` with _CloudFormation_ that has a lot of _Parameters_, you need to pass huge amount of command arguments to fill it, or prepare a _JSON_ file with all those values.

We would like to have it available as a command in our tool - we would like to generate a file (sending output to the `stdout`) or command line arguments string only. Values should be read from the standard input (both - interactively or passed as a `stdin` via pipe or something similar).

**Comment by maxiwoj** [comment]
Do we want to support explicit parameter list as a cli parameter to perun?
Would we like to ask interactively for parameters during stack creation when parameters are not provided by the user?

**Comment by afronski** [comment]
Yup, you're right in both cases.

**Comment by afronski** [comment]
Closed with #94.
