### ISSUE TITLE
Showing CloudFormation execution progress in the CLI

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#17]
Goal of this task is to show output of the _CloudFormation_ run in the console (with colors 😉). It is like an interactive mode for running it, without switching to the browser. 

It may require additional setup - like _SNS_ topic, subscribing to it or calling periodically `describe-stack-events`.
  - Resources:
    - https://stackoverflow.com/questions/33664226/how-to-send-sns-notification-after-cloud-formation-is-completed
    - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-monitor-stack.html#using-cfn-updating-stacks-monitor-stack.CLI

**Comment by maxiwoj** [comment]
Do we want to support colors dependable on the state (ex. CREATE_FAILED would be red) or just a pretty table print?

**Comment by afronski** [comment]
Having colors would be awesome. _GFI_.
