### ISSUE TITLE
Update ResourceSpecificationURL

### ISSUE THREAD

**Issue by SylwiaGargula** [Appliscale/perun#184]
We can try to download regions and links in a similar way how it's in https://github.com/Appliscale/cloud-security-audit.

**Comment by SylwiaGargula** [comment]
https://trello.com/c/lSrHfAhE/102-update-resourcespecificationurl

**Comment by SylwiaGargula** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update ResourceSpecificationURL](https://trello.com/c/lSrHfAhE/102-update-resourcespecificationurl)

**Comment by maxiwoj** [comment]
closed by https://github.com/Appliscale/perun/pull/186
