### ISSUE TITLE
Name, motivation and clear goal

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#3]
We need:

- A _catchy name_ for that project. 😉
  - "_Catchyness_" is one thing - it needs to have nice name / shortcut for a command line interface.
- Motivation and rationale - why we created it in the first place?
  - Section in _README.md_ and maybe longer explanation on the wiki if needed.
- Clear goal - with what we want to help via this tool?
  - Section in _README.md_ and maybe longer explanation on the wiki if needed.

**Comment by afronski** [comment]
Possible options:

- [Name from a particular type of clouds](https://en.wikipedia.org/wiki/List_of_cloud_types) - I really like this idea, that I've picked it for naming releases / milestones.
- _Weather_ related: _Weather_, _Pressure_, _Atmospheric Front_, _Nephology_ (science about clouds).
- _Entities_ related: _Thumper_ (in meaning of giant), _Colossus_.
- _Deities_ related: 
  - _Slavic_: _Perun_, _Triglav_, _Dazhbog_ (deities of sky, wind, storm).
  - _Nordic_: _Njord_ (deity of wind).

**Comment by mwpolcik** [comment]
_perun_ +1

**Comment by afronski** [comment]
It looks like there is a competition - https://github.com/search?utf8=%E2%9C%93&q=perun&type= (most known would be https://perun.io).

**Comment by pfigwer** [comment]
Maybe something like CFPerun or PerunCloud?
