### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#44]
Currently, we need to build `perun` locally in order to use it. It is very inconvenient - we would like to distribute it in packaged form (binary distribution).

We would like to support:

- [x] `brew` (done by @ppikula)
- [x] `rpm`
- [x] `deb`
- [x] *Chocolatey*

For other cases - compiling from source. 

It is related to #28 as it will require cross-platform building and integration tests.

**Comment by SylwiaGargula** [comment]
Chocolatey: https://github.com/Appliscale/perun-Chocolatey

**Comment by SylwiaGargula** [comment]
rpm: https://github.com/Appliscale/perun-rpm
deb: https://github.com/Appliscale/perun-dpkg
I'll add how to publish packages.
