### ISSUE TITLE
New YAML parser

### ISSUE THREAD

**Issue by pfigwer** [Appliscale/perun#56]
Curently we are using ghodss/yaml library for unmarshalling yaml files into GO structures. It is nice and easy to use, but it converts YAML to JSON then uses JSON to unmarshal into an object and cause  some problems in our case (see https://github.com/Appliscale/perun/issues/23). We need a library, that converts YAML straight into GO structures. https://github.com/go-yaml/yaml is a good candidate. So lets start with trying it out in our code! 😃

**Comment by jlampar** [comment]
The previous parsing library _goods/yaml_ was replaced by recommended library _go-yaml/yaml_ and validation ran swiftly with additional medical treatment on file _template.go_. Tags were added to field definitions in a following manner:

type StructName struct {
	...
	fieldName fieldType `yaml:"fieldName"`
	...
}

Those tags were required for all the fields to parse the YAML. It was tested if the tags would left JSON parsing intact and they did (both parsing functions are referring to the same struct). It was tested if the new parsing library reads and includes _!Sub_ and _!FindInMap_ tags in the struct and unfortunately it isn't.
