### ISSUE TITLE
Adding support for short version of intrinsic functions missing from goformation 

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#79]
Missing support for functions in our `intrinsicsolver` module:

- `!Ref`
- `!GetAtt`
- `!ImportValue`

**Comment by jlampar** [comment]
The first approximation was proposed in #82, where those functions are treated as not yet solvable and thus omited by parser. If those functions would be fixed someday inside `goformation` library, this approach prevents us from the coding crossfire.
