### ISSUE TITLE
Mode parameters should be available also with explicit flag names 

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#84]
I would like to open discussion here about the usability of our _CLI_ modes.

Currently, most of the modes uses implicit order of parameters, e.g.,

```
perun convert A.json B.yaml
perun convert A.yaml B.json --pretty-print
```

That's good. However, I would love to have it available also under explicit parameter names:

```
perun convert A.json B.yaml
perun convert --from=A.json --to=B.yaml

perun convert A.yaml B.json --pretty-print
perun convert --from=A.yaml --to=B.json --pretty-print
```

I know that will complicate the implementation, but maybe advantages are more significant than drawbacks.

**Comment by maxiwoj** [comment]
AFAIK it will significantly complicate the code and the usage of the tool - the kingpin cli arguments parser is not designed for this, but I'll create a quick PR for everyone to see.
