### ISSUE TITLE
MFA should not be required parameter 

### ISSUE THREAD

**Issue by mwpolcik** [Appliscale/perun#91]
When running:
```bash
$ perun create-stack my-stack-name path/to/template --region us-east-1 --profile some-profile
```
I got:
```
 INFO: Configuration file from the following location will be used: /Users/myuser/.config/perun/main.yaml
ERROR: There is no mfa_serial for the profile some-profile-long-term
```
If you don't specify `--mfa` the check for mfa_serial should be probably omitted. It is up to users if they are going to use mfa or not. 

Additionally if something is throwing an error I would expect the whole command to fail, but in this case the stack was created.

**Comment by afronski** [comment]
> Additionally if something is throwing an error I would expect the whole command to fail, but in this case the stack was created.

THIS. :wink:

**Comment by maxiwoj** [comment]
Do we want to force the user to type '--mfa' always when they use MFA Authentication?

**Comment by maxiwoj** [comment]
closed by https://github.com/Appliscale/perun/pull/101
